monolog:
  # Configure the log channels
  channels:
    # Enable logging for the deprecation channel
    - deprecation

  # Define handlers for various log channels
  handlers:
    # Main handler for general logs
    main:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: debug
      # Exclude the 'mailer' channel from the main log
      channels: ["!mailer"]

    # Separate handler for mailer logs
    mailer:
      type: stream
      path: "%kernel.logs_dir%/mailer.log"
      level: debug
      channels: ["mailer"]

    # Additional handler for deprecation logs
    deprecation:
      type: stream
      path: "%kernel.logs_dir%/deprecation.log"
      level: info
      channels: ["deprecation"]

when@dev:
  monolog:
    handlers:
      main:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.log"
        level: debug
        channels: ["!event"]
      # uncomment to get logging in your browser
      # you may have to allow bigger header sizes in your Web server configuration
      #firephp:
      #    type: firephp
      #    level: info
      #chromephp:
      #    type: chromephp
      #    level: info
      console:
        type: console
        process_psr_3_messages: false
        channels: ["!event", "!doctrine", "!console"]

when@test:
  monolog:
    handlers:
      main:
        type: fingers_crossed
        action_level: error
        handler: nested
        excluded_http_codes: [404, 405]
        channels: ["!event"]
      nested:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.log"
        level: debug

when@prod:
  monolog:
    handlers:
      main:
        type: fingers_crossed
        action_level: error
        handler: nested
        excluded_http_codes: [404, 405]
        buffer_size: 50 # How many messages should be saved? Prevent memory leaks
      nested:
        type: stream
        path: php://stderr
        level: debug
        formatter: monolog.formatter.json
      console:
        type: console
        process_psr_3_messages: false
        channels: ["!event", "!doctrine"]
      deprecation:
        type: stream
        channels: [deprecation]
        path: php://stderr
        formatter: monolog.formatter.json
