services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: stubborn
    ports:
      - "8000:80"
    volumes:
      - /d/ExercicesVSC/Devoirs/Stubborn_project/public:/var/www/public
    networks:
      - dev
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin
    container_name: stubborn_phpmyadmnin
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - dev

  db:
    image: mysql
    container_name: stubborn_db
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - dev

networks:
  dev:

volumes:
  db-data:
