services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stubborn
    ports:
      - "8000:80"
    volumes:
      - /d/ExercicesVSC/Devoirs/Stubborn_project/public:/var/www/public
    networks:
      - dev

networks:
  dev:

volumes:
  db-data:
