services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stubborn
    ports:
      - "8000:80"
    volumes:
      # - /d/ExercicesVSC/Devoirs/Stubborn_project/public:/var/www/public
    networks:
      - dev

  messenger:
    image: php:8.2-cli
    container_name: stubborn_messenger
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: ["php", "bin/console", "messenger:consume", "async"]
    networks:
      - app-network

networks:
  dev:

volumes:
  db-data:
